version: "3.9"

services:
  laravelapp:
    container_name: split-calendar
    volumes:
      - ./:/var/www/html
    build: .
    restart: always
    ports:
      - 8003:80
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - laravel
    environment:
      - DB_HOST=mysql

  mysql:
    container_name: mysql_calendar
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - pgdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    container_name: phpmyadmin_calendar
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    networks:
      - laravel
      
  vite:
    container_name: vite_calendar
    build:
      context: .
    command: npm run dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 5173:5173
    networks:
      - laravel
      
volumes:
  pgdata: {}
    
networks:
  laravel: